// defines the structure of the prayer request object
// id is not included here because it is auto generated by the database
export interface PrayerRequest {
  title: string; // short title of the prayer request
  description: string; // full description of the prayer request
  category: string; // category (health, work, family, etc.)
  dateSubmitted: string; // date the prayer request was submitted
  isAnswered: boolean; // whether the prayer request has been answered
  priorityLevel: number; // priority level of the prayer request (1-5)
}